on:
  push:
    branches:
      - main

jobs:
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip'  # caching pip dependencies
      - run: pip install -r examples/requirements.txt
      - run: pip install pylint
      - run: pylint examples/*.py
